# Build and publish the dockerfile
name: publish
on:
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Get git short hash
      id: shorthash
      run: |
        echo "shorthash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
    
    - name: Login to GH container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        tags: |
          ${{ format('ghcr.io/kwest-ng/haskell-dev-tools:9.4.7-{0}', steps.shorthash.outputs.shorthash) }}
          ghcr.io/kwest-ng/haskell-dev-tools:9.4.7-latest
        push: true
        context: ./src
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - # Hack fix until these issues are resolved
      # This prevents the cache from growing too large, which causes early
      # evictions and therefore cache misses. This is mostly to prevent long
      # build times when the last change is not a new tool install.
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
